Split login & registration to two pages
czmud/SCQuorum pull request #1
Opened 2022-09-13 16:17 UTC by czmud

-created new template for registration to make login page cleaner
-updated Users controller to handle routes/rendering of registration.html

2022-09-13 17:05 UTC, bryankenote requested changes

2022-09-13 17:05 UTC, bryankenote commented on flask_app/templates/registration.html
> +                </table>
We should generally try to avoid using html tables for layout. We should limit their use to actual tables. Here are some [examples](https://www.thoughtco.com/dont-use-tables-for-layout-3468941) for why, but most notably it is difficult to make the ui responsive to various screen sizes.

You should use either flex (most of the time) and grid (usually overkill) for layout.

2022-09-14 03:56 UTC, czmud commented on flask_app/templates/registration.html
> +                </table>
Updated forms to use display flex divs (bootstrap).

2022-09-14 04:01 UTC, bryankenote approved these changes

2022-09-14 04:07 UTC, merged